# Generated by Django 4.2.8 on 2023-12-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tournamentTypeValue', models.CharField(max_length=30, null='BO1')),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('begginingdate', models.DateField(null=True)),
                ('endingdate', models.DateField(null=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='games.games')),
                ('tournamentType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournamentType', to='tournaments.tournamenttype')),
            ],
        ),
    ]
