# Generated by Django 4.2.8 on 2023-12-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='users',
            field=models.ManyToManyField(related_name='attended_users', to='users.users'),
        ),
    ]
