# Generated by Django 4.2.8 on 2024-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='thumbnail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
