# Generated by Django 4.2.8 on 2024-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournaments_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
