# Generated by Django 4.2.8 on 2023-12-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userno', models.IntegerField()),
                ('nickname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password_sha256', models.CharField(max_length=255)),
                ('password_raw', models.CharField(max_length=255)),
                ('balance', models.IntegerField()),
                ('favorite_game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorite_game', to='games.games')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='teams.teams')),
            ],
        ),
    ]
