# Generated by Django 4.2.8 on 2024-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tournaments_attendy',
            field=models.ManyToManyField(related_name='attended_users', to='tournaments.tournaments'),
        ),
    ]
